[2025-05-14T00:08:19.600+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:19.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:08:19.771+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:19.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:20.069+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:20.013+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:08:20.215+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:21.565+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.563+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:earthquake_etl_pipeline
[2025-05-14T00:08:21.598+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.598+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:earthquake_etl_pipeline
[2025-05-14T00:08:21.624+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.624+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:earthquake_etl_pipeline
[2025-05-14T00:08:21.626+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.626+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:08:21.699+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.699+0000] {dag.py:3058} INFO - Creating ORM DAG for earthquake_etl_pipeline
[2025-05-14T00:08:21.710+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:21.710+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:08:21.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 2.277 seconds
[2025-05-14T00:08:52.578+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:52.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:08:52.653+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:52.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:53.028+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:53.024+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:08:53.029+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:08:53.189+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:53.188+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:08:53.593+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:08:53.593+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:08:53.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.268 seconds
[2025-05-14T00:09:23.864+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:23.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:09:23.868+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:23.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:23.890+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:23.890+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:09:23.891+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:23.915+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:23.914+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:09:23.930+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:23.930+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:09:23.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.094 seconds
[2025-05-14T00:09:54.605+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:54.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:09:54.608+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:54.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:54.628+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:54.627+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:09:54.628+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:09:54.653+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:54.652+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:09:54.666+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:09:54.666+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:09:54.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.148 seconds
[2025-05-14T00:10:24.855+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:24.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:10:24.859+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:24.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:24.881+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:24.879+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:10:24.882+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:24.907+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:24.906+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:10:24.925+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:24.924+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:10:24.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.105 seconds
[2025-05-14T00:10:55.927+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:55.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:10:55.933+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:55.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:55.965+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:55.964+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:10:55.967+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:10:55.995+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:55.995+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:10:56.012+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:10:56.012+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:10:56.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.124 seconds
[2025-05-14T00:11:26.541+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:26.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:11:26.546+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:26.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:27.030+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:26.579+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:11:27.032+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:27.058+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:27.058+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:11:27.076+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:27.076+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:11:27.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.577 seconds
[2025-05-14T00:11:57.511+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:57.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:11:57.517+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:57.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:57.545+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:57.544+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:11:57.547+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:11:57.584+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:57.584+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:11:57.599+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:11:57.598+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:11:57.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.120 seconds
[2025-05-14T00:12:27.728+0000] {processor.py:161} INFO - Started process (PID=512) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:27.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:12:27.735+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:27.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:27.768+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:27.767+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:12:27.769+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:27.796+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:27.796+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:12:27.812+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:27.812+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:12:27.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.122 seconds
[2025-05-14T00:12:58.451+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:58.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:12:58.456+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:58.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:58.490+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:58.489+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:12:58.491+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:12:58.518+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:58.517+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:12:58.539+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:12:58.539+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:12:58.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.138 seconds
[2025-05-14T00:13:29.028+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:29.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:13:29.032+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:29.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:29.058+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:29.056+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:13:29.059+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:29.086+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:29.085+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:13:29.100+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:29.100+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:13:29.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.101 seconds
[2025-05-14T00:13:59.553+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:59.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:13:59.559+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:59.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:59.582+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:59.581+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:13:59.583+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:13:59.605+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:59.605+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:13:59.621+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:13:59.620+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:13:59.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.110 seconds
[2025-05-14T00:14:30.594+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:14:30.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:14:30.597+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:14:30.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:14:30.619+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:14:30.618+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:14:30.620+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:14:30.644+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:14:30.643+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:14:30.659+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:14:30.659+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:14:30.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.097 seconds
[2025-05-14T00:15:01.146+0000] {processor.py:161} INFO - Started process (PID=792) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:01.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:15:01.152+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:01.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:01.172+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:01.171+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:15:01.173+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:01.203+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:01.202+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:15:01.223+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:01.223+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:15:01.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.107 seconds
[2025-05-14T00:15:31.766+0000] {processor.py:161} INFO - Started process (PID=848) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:31.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:15:31.771+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:31.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:31.806+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:31.805+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:15:31.807+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:15:31.838+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:31.837+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:15:31.853+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:15:31.853+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:15:31.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.128 seconds
[2025-05-14T00:16:02.536+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:02.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:16:02.562+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:02.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:02.847+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:02.832+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:16:02.884+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:02.958+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:02.952+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:16:03.034+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:03.034+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:16:03.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.618 seconds
[2025-05-14T00:16:33.301+0000] {processor.py:161} INFO - Started process (PID=960) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:33.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:16:33.305+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:33.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:33.329+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:33.328+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:16:33.330+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:33.352+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:33.352+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:16:33.365+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:33.365+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:16:33.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.092 seconds
[2025-05-14T00:16:37.798+0000] {processor.py:161} INFO - Started process (PID=967) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:37.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:16:37.802+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:37.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:37.842+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:37.841+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:16:37.842+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:16:37.985+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:37.985+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:16:38.050+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:16:38.050+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:16:38.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.325 seconds
[2025-05-14T00:17:08.399+0000] {processor.py:161} INFO - Started process (PID=1022) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:08.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:17:08.404+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:08.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:08.437+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:08.436+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:17:08.438+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:08.473+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:08.472+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:17:08.507+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:08.506+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:17:08.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.156 seconds
[2025-05-14T00:17:38.794+0000] {processor.py:161} INFO - Started process (PID=1079) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:38.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:17:38.799+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:38.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:38.821+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:38.820+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:17:38.822+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:17:38.857+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:38.857+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:17:38.874+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:17:38.873+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:17:38.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.107 seconds
[2025-05-14T00:18:08.981+0000] {processor.py:161} INFO - Started process (PID=1135) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:08.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:18:08.991+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:08.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:09.110+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:09.109+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:18:09.116+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:09.149+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:09.149+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:18:09.175+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:09.175+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:18:09.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.252 seconds
[2025-05-14T00:18:39.511+0000] {processor.py:161} INFO - Started process (PID=1192) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:39.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:18:39.515+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:39.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:39.542+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:39.540+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:18:39.542+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:18:39.570+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:39.569+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:18:39.591+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:18:39.591+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:18:39.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.117 seconds
[2025-05-14T00:19:09.710+0000] {processor.py:161} INFO - Started process (PID=1248) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:09.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:19:09.713+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:09.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:09.736+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:09.735+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:19:09.737+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:09.772+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:09.771+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:19:09.792+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:09.792+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:19:09.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.117 seconds
[2025-05-14T00:19:40.095+0000] {processor.py:161} INFO - Started process (PID=1304) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:40.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:19:40.100+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:40.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:40.124+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:40.124+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:19:40.125+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:19:40.149+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:40.149+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:19:40.163+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:19:40.162+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:19:40.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.096 seconds
[2025-05-14T00:20:11.075+0000] {processor.py:161} INFO - Started process (PID=1360) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:11.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:20:11.079+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:11.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:11.108+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:11.107+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:20:11.109+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:11.158+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:11.158+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:20:11.175+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:11.175+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:20:11.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.191 seconds
[2025-05-14T00:20:41.869+0000] {processor.py:161} INFO - Started process (PID=1416) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:41.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:20:41.879+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:41.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:41.914+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:41.912+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:20:41.915+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:20:41.944+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:41.944+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:20:41.963+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:20:41.963+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:20:42.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.151 seconds
[2025-05-14T00:21:12.270+0000] {processor.py:161} INFO - Started process (PID=1472) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:12.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:21:12.274+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:12.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:12.295+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:12.294+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:21:12.296+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:12.316+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:12.316+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:21:12.330+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:12.330+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:21:12.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.088 seconds
[2025-05-14T00:21:42.930+0000] {processor.py:161} INFO - Started process (PID=1528) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:42.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:21:42.933+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:42.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:42.959+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:42.958+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:21:42.960+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:21:42.982+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:42.982+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:21:42.996+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:21:42.996+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:21:43.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.104 seconds
[2025-05-14T00:22:13.131+0000] {processor.py:161} INFO - Started process (PID=1582) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:13.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:22:13.136+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:13.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:13.161+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:13.159+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:22:13.161+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:13.188+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:13.188+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:22:13.204+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:13.204+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:22:13.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.109 seconds
[2025-05-14T00:22:43.471+0000] {processor.py:161} INFO - Started process (PID=1633) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:43.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:22:43.478+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:43.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:43.504+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:43.503+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:22:43.505+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:22:43.531+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:43.530+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:22:43.548+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:22:43.548+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:22:43.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.147 seconds
[2025-05-14T00:23:14.516+0000] {processor.py:161} INFO - Started process (PID=1689) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:14.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:23:14.525+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:14.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:14.554+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:14.553+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:23:14.554+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:14.581+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:14.581+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:23:14.610+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:14.609+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:23:14.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.154 seconds
[2025-05-14T00:23:45.503+0000] {processor.py:161} INFO - Started process (PID=1745) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:45.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-14T00:23:45.506+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:45.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:45.531+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:45.530+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-14T00:23:45.532+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-14T00:23:45.562+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:45.562+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-14T00:23:45.579+0000] {logging_mixin.py:188} INFO - [2025-05-14T00:23:45.579+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-14T00:23:45.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.106 seconds
