[2025-05-13T21:09:05.829+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:05.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:09:05.838+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:05.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:05.974+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:05.949+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:09:06.068+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:06.838+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.835+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:earthquake_etl_pipeline
[2025-05-13T21:09:06.878+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.878+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:earthquake_etl_pipeline
[2025-05-13T21:09:06.898+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.898+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:earthquake_etl_pipeline
[2025-05-13T21:09:06.900+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.900+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:09:06.927+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.926+0000] {dag.py:3058} INFO - Creating ORM DAG for earthquake_etl_pipeline
[2025-05-13T21:09:06.928+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:06.928+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:09:06.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.172 seconds
[2025-05-13T21:09:37.654+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:41.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:09:53.666+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:47.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:53.752+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:53.737+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:09:53.755+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:09:55.071+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:55.070+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:09:55.093+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:09:55.092+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:09:55.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 17.799 seconds
[2025-05-13T21:11:24.409+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:11:24.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:11:24.428+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:11:24.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:11:24.703+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:11:24.675+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:11:24.707+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:11:55.321+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:11:55.314+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:11:55.830+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:11:55.829+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:11:56.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 31.872 seconds
[2025-05-13T21:14:15.917+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:15.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:14:16.033+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:16.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:16.526+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:16.516+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:14:16.592+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:17.380+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:17.380+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:14:17.498+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:17.498+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:14:17.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.913 seconds
[2025-05-13T21:14:47.943+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:47.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:14:47.971+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:47.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:48.210+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:48.206+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:14:48.211+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:14:48.342+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:48.342+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:14:48.406+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:14:48.406+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:14:48.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.595 seconds
[2025-05-13T21:15:19.425+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:19.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:15:19.428+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:19.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:19.449+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:19.448+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:15:19.450+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:19.471+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:19.471+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:15:19.484+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:19.484+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:15:19.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.113 seconds
[2025-05-13T21:15:50.366+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:50.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:15:50.370+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:50.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:50.400+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:50.399+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:15:50.401+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:15:50.427+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:50.426+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:15:50.444+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:15:50.444+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:15:50.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.145 seconds
[2025-05-13T21:16:20.752+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:20.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:16:20.763+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:20.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:20.792+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:20.791+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:16:20.793+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:20.822+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:20.821+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:16:20.839+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:20.838+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:16:20.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.122 seconds
[2025-05-13T21:16:51.258+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:51.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:16:51.261+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:51.261+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:51.293+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:51.292+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:16:51.294+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:16:51.324+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:51.324+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:16:51.340+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:16:51.340+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:16:51.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.121 seconds
[2025-05-13T21:17:21.554+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:21.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:17:21.558+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:21.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:21.589+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:21.588+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:17:21.590+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:21.644+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:21.643+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:17:21.662+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:21.662+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:17:21.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.154 seconds
[2025-05-13T21:17:52.142+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:52.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:17:52.157+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:52.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:52.194+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:52.193+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:17:52.196+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:17:52.229+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:52.229+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:17:52.247+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:17:52.247+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:17:52.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.159 seconds
[2025-05-13T21:18:22.908+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:22.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:18:22.911+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:22.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:22.941+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:22.939+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:18:22.942+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:22.977+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:22.977+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:18:22.998+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:22.997+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:18:23.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.140 seconds
[2025-05-13T21:18:53.171+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:53.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:18:53.175+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:53.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:53.218+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:53.216+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:18:53.222+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:18:53.253+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:53.252+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:18:53.276+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:18:53.275+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:18:53.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.152 seconds
[2025-05-13T21:19:24.067+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:19:24.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:19:24.071+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:19:24.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:19:24.098+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:19:24.096+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:19:24.117+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:19:24.142+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:19:24.141+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:19:24.156+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:19:24.156+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:19:24.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.150 seconds
[2025-05-13T21:57:48.200+0000] {processor.py:161} INFO - Started process (PID=655) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:57:48.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:57:48.389+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:57:48.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:57:49.208+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:57:49.199+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:57:49.213+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:57:49.768+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:57:49.767+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:57:50.370+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:57:50.369+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:57:50.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 2.886 seconds
[2025-05-13T21:58:21.355+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:21.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:58:21.384+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:21.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:21.455+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:21.450+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:58:21.455+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:21.489+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:21.489+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:58:21.507+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:21.507+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:58:21.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.258 seconds
[2025-05-13T21:58:51.888+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:51.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:58:51.893+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:51.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:51.934+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:51.931+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:58:51.935+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:58:51.968+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:51.967+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:58:51.982+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:58:51.982+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:58:52.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.150 seconds
[2025-05-13T21:59:22.510+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:59:22.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-05-13T21:59:22.516+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:59:22.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:59:22.548+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:59:22.546+0000] {templater.py:95} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/scripts/download_data.sh
[2025-05-13T21:59:22.549+0000] {processor.py:840} INFO - DAG(s) 'earthquake_etl_pipeline' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-05-13T21:59:22.587+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:59:22.586+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-05-13T21:59:22.606+0000] {logging_mixin.py:188} INFO - [2025-05-13T21:59:22.606+0000] {dag.py:3823} INFO - Setting next_dagrun for earthquake_etl_pipeline to None, run_after=None
[2025-05-13T21:59:22.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.141 seconds
